name: "Build and Push"

inputs:
  VERSION_MAJOR:
    required: true
  DATE_STAMP:
    required: true
  IMAGE_REGISTRY:
    required: true
  VARIANT:
    required: true
  REGISTRY_USER:
    required: true
  REGISTRY_PASSWORD:
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo "VARIANT=--platform ${{ env.PLATFORM }}" >> "$GITHUB_ENV"

        # quay.io/almalinuxorg/almalinux-bootc-rpi
        IMAGE_DEST=${{ inputs.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        echo "IMAGE_DEST=${IMAGE_DEST}" >> "$GITHUB_ENV"

        ARCH=${{ matrix.ARCH }}
        echo "CLEAN_ARCH=${ARCH//\//_}" >> "$GITHUB_ENV"

    - name: Log in to registry
      if: github.event_name != 'pull_request' && github.event_name != 'release'
      shell: bash
      run: sudo podman login ${{ inputs.IMAGE_REGISTRY }} -u ${{ inputs.REGISTRY_USER }} -p ${{ inputs.REGISTRY_PASSWORD }}

    - name: Check update
      shell: bash
      run: |
        # 'dnf check-update'
        # exit codes:
        #   0 - no updates
        #   100 - updates available
        #   125 - tag/platform not found
        #   127 - command not found
        res=0
        if [ "${{ github.event_name }}" != "pull_request" -a "${{ github.event_name }}" != "release" ]; then
          sudo podman run ${{ env.VARIANT }} --quiet --rm ${{ inputs.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }} dnf check-update || res=$?
        else
          res=100
        fi
        echo "res=${res}" >> "$GITHUB_ENV"
        echo "Exit code: '$res'"

    - name: Get info
      id: info
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        INFO=$(sudo podman run ${{ env.VARIANT }} --quiet --rm quay.io/almalinuxorg/${{ inputs.VERSION_MAJOR }}-base bash -c "dnf upgrade -y almalinux-release && rpm -q almalinux-gpg-keys && cat /etc/os-release" || true)
        echo "$INFO"

        echo "id=$(echo "$INFO" | grep "^ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "version-id=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "long-version=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"').${{ inputs.DATE_STAMP }}.0" >> $GITHUB_OUTPUT

    - name: Build image
      id: build
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        BUILD_TIME=$(date -Iseconds)

        # define a multiline variable with heredoc
        LABELS=$(cat <<EOF
        redhat.id=${{ steps.info.outputs.id }}
        redhat.version-id=${{ steps.info.outputs.version-id }}
        version=${{ steps.info.outputs.version-id }}
        release=${{ steps.info.outputs.version-id }}
        build-date=${BUILD_TIME}
        org.opencontainers.image.created=${BUILD_TIME}
        org.opencontainers.image.version=${{ steps.info.outputs.long-version }}
        org.opencontainers.image.source=${{ github.repositoryUrl }}
        org.opencontainers.image.title=${{ env.IMAGE_NAME }}
        org.opencontainers.image.url=${{ github.event.repository.html_url }}
        EOF
        )

        while IFS= read -r label; do
          ALL_LABELS="$ALL_LABELS --label=\"$label\" --annotation=\"$label\""
        done <<< "$LABELS"

        make image \
          PLATFORM=${{ env.PLATFORM }} \
          LABELS="${ALL_LABELS}" \
          IMAGE_NAME=${{ env.IMAGE_NAME }} \
          VERSION_MAJOR=${{ inputs.VERSION_MAJOR }} \
          VARIANT=${{ inputs.VARIANT }}

        echo "image-id=$(cat /tmp/image-id)" >> $GITHUB_OUTPUT

    - name: rechunk image
      id: rechunk
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        make rechunk \
          PLATFORM=${{ env.PLATFORM }} \
          IMAGE_NAME=${{ env.IMAGE_NAME }}

        echo "image-id=sha256:$(sudo podman image inspect ${{ env.IMAGE_NAME }} -f "{{.Id}}")" >> $GITHUB_OUTPUT

    - name: Build Image Tars
      id: tars
      if: github.event_name == 'pull_request' || github.event_name == 'release' 
      shell: bash
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
      run: |
        sudo podman tag \
          ${{ env.IMAGE_ID }} \
          localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} && \
        sudo podman save \
          ${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} > \
          /tmp/image-${{ env.IMAGE_NAME }}-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.tar

    - name: Build os image
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'release'
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
      run: |
        mkdir -p output && \
        cp bib-config.toml output/ && \
        sudo podman build \
           -t localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-bootstrap-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} \
           -f ${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image/Dockerfile \
           --build-arg=BASE=localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} \
           ${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image && \
        sudo podman run \
           --rm \
           -i \
           --privileged \
           --security-opt label=type:unconfined_t \
           -v $(pwd)/output:/output \
           -v /var/lib/containers/storage:/var/lib/containers/storage \
           quay.io/centos-bootc/bootc-image-builder:latest \
           --config /output/bib-config.toml \
           --type raw \
           --rootfs xfs \
           --local \
           localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-bootstrap-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} && \
        ls -l output/image && \
        sudo cp output/image/disk.raw /tmp/image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw && \
        sudo mv output/image/disk.raw /tmp/image-${{ env.IMAGE_NAME }}4-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw && \
        mkdir -p /tmp/mnt && \
        LOOP=$(sudo losetup -f --show -P /tmp/image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw) && \
        sudo fatlabel ${LOOP}p1 "CIDATA" && \
        sudo mount ${LOOP}p1 /tmp/mnt && \
        sudo touch /tmp/mnt/meta-data && \
        sudo cp $(pwd)/${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image/user-data /tmp/mnt/ && \
        sudo cp $(pwd)/${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image/README.txt /tmp/mnt/ && \
        cd /tmp && \
        curl -L -O https://github.com/worproject/rpi5-uefi/releases/download/v0.3/RPi5_UEFI_Release_v0.3.zip && \
        sudo /bin/bash -c "cd mnt && unzip ../RPi5_UEFI_Release_v0.3.zip" && \
        sudo podman run \
          --rm \
          -i \
          -v /tmp/mnt:/tmp \
          --entrypoint /bin/bash \
          localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} \
          -c "cp /usr/share/raspberrypi2-kernel*/*/boot/bcm2712-rpi-5-b.dtb /tmp/bcm2712-rpi-5-b.dtb" && \
        sudo umount /tmp/mnt
        LOOP=$(sudo losetup -f --show -P /tmp/image-${{ env.IMAGE_NAME }}4-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw) && \
        sudo fatlabel ${LOOP}p1 "CIDATA" && \
        sudo mount ${LOOP}p1 /tmp/mnt && \
        sudo touch /tmp/mnt/meta-data && \
        sudo cp $(pwd)/${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image/user-data /tmp/mnt/ && \
        sudo cp $(pwd)/${{ inputs.VERSION_MAJOR }}-rpi/bootstrap-image/README.txt /tmp/mnt/ && \
        cd /tmp && \
        sudo podman run \
          --rm \
          -i \
          -v /tmp/mnt:/tmp \
          --entrypoint /bin/bash \
          localhost/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} \
          -c "cp /usr/share/raspberrypi2-kernel*/*/boot/*.dtb /tmp/ && cp -a /usr/share/raspberrypi2-kernel*/*/boot/* /tmp/" && \
        curl -o uboot.tar.bz2 https://ftp.denx.de/pub/u-boot/u-boot-2025.07.tar.bz2 && \
        tar -jxvf uboot.tar.bz2 && \
        cd u-boot-u-boot-2025.07/ && \
        make rpi_arm64_defconfig && \
        ls -l && \
        exit -1 && \
        sudo umount /tmp/mnt

    - name: Compress os image
      shell: bash
      if: github.event_name == 'release'
      run: |
        sudo xz /tmp/image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw

    - name: Run Image
      id: run
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
      run: |
        sudo podman run ${{ env.VARIANT }} --rm -ti ${{ env.IMAGE_ID }} bootc --version

        INFO=$(sudo podman run ${{ env.VARIANT }} --rm ${{ env.IMAGE_ID }} bash -c "rpm -q almalinux-gpg-keys && cat /etc/os-release")
        echo "$INFO"

        echo "id=$(echo "$INFO" | grep "^ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "version-id=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "long-version=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"').${{ inputs.DATE_STAMP }}.0" >> $GITHUB_OUTPUT
        echo "vendor=$(echo "$INFO" | grep "^VENDOR_NAME=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Push to registry
      id: push
      if: ${{ (env.res != 0 || github.event_name == 'workflow_dispatch') && github.event_name != 'pull_request' && github.event_name != 'release' }}
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
        VERSION: ${{ steps.run.outputs.version-id }}
      shell: bash
      run: |
        # The push fails for unknown reasons sometimes, so we'll retry it a few times
        for i in {1..5}; do
          sudo podman push --digestfile=/tmp/digestfile ${{ env.IMAGE_ID }} \
            docker://${IMAGE_DEST}:${{ env.VERSION }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} && break || sleep $((10*i))
        done
        [ -f /tmp/digestfile ] || exit 1
        echo "digest=$(cat /tmp/digestfile)" >> $GITHUB_OUTPUT
        sudo podman inspect ${{ env.IMAGE_ID }}

    - name: Create Job Outputs
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        mkdir -p /tmp/outputs/digests

        jq -n --arg platform "${{ matrix.ARCH }}" \
          --arg major "${{ inputs.VERSION_MAJOR }}" \
          --arg digest "${{ steps.push.outputs.digest }}" \
          --arg id "${{ steps.run.outputs.id }}" \
          --arg version "${{ steps.run.outputs.version-id }}" \
          --arg long_version "${{ steps.run.outputs.long-version }}" \
          --arg vendor "${{ steps.run.outputs.vendor }}" \
          --arg image_id "${{ steps.rechunk.outputs.image-id }}" \
          '{($platform): {digest: $digest, id: $id, version: $version, major: $major, long_version: $long_version, vendor: $vendor, image_id: $image_id}}' \
          > /tmp/outputs/digests/${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}.json

        cat /tmp/outputs/digests/${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}.json

    - name: Upload Container Image Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'release' }}
      with:
        name: image-${{ env.IMAGE_NAME }}-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.tar
        path: /tmp/image-${{ env.IMAGE_NAME }}-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.tar
        retention-days: 1
        if-no-files-found: error

    - name: Upload Bootstrap Image Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw
        path: /tmp/image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw

    - name: Upload Bootstrap Image Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'release' }}
      with:
        name: image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw.xz
        path: /tmp/image-${{ env.IMAGE_NAME }}5-${{ inputs.VERSION_MAJOR }}${{ env.VERSION_MINOR }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }}.raw.xz

    - name: Upload Output Artifacts
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}
        retention-days: 1
        if-no-files-found: error
        path: |
          /tmp/outputs/digests/*.json
