FROM quay.io/almalinuxorg/10-kitten-base:10-kitten as repos
FROM quay.io/centos-bootc/centos-bootc:stream10 as builder

RUN rm -rf /etc/yum.repos.d/*

COPY --from=repos /etc/yum.repos.d/*.repo /etc/yum.repos.d/
COPY --from=repos /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-10 /etc/pki/rpm-gpg

COPY 10-kitten-rpi/almalinux-raspberrypi.repo  /etc/yum.repos.d/
COPY 10-kitten-rpi/almalinux-10-kitten-rpi.yaml /usr/share/doc/bootc-base-imagectl/manifests/
COPY 10-kitten-rpi/kernel.yaml /usr/share/doc/bootc-base-imagectl/manifests/minimal/

RUN sed -i 's/efibootmgr//g' /usr/share/doc/bootc-base-imagectl/manifests/minimal/bootupd.yaml

RUN /usr/libexec/bootc-base-imagectl build-rootfs --manifest=almalinux-10-kitten-rpi /target-rootfs

RUN \
  cd /tmp && \
  curl -L -o firmware.tar.gz https://github.com/RPi-Distro/firmware-nonfree/archive/223ccf3a3ddb11b3ea829749fbbba4d65b380897/firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897.tar.gz && \
  tar -zxvf firmware.tar.gz && \
  ln -s cyfmac43455-sdio-standard.bin firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/cypress/cyfmac43455-sdio.bin && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.bin /target-rootfs/usr/lib/firmware/brcm/ && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.clm_blob /target-rootfs/usr/lib/firmware/brcm/ && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.txt /target-rootfs/usr/lib/firmware/brcm/ && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.bin /target-rootfs/usr/lib/firmware/brcm/ && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.clm_blob /target-rootfs/usr/lib/firmware/brcm/ && \
  install -c -m 644 firmware-nonfree-223ccf3a3ddb11b3ea829749fbbba4d65b380897/debian/config/brcm80211/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt /target-rootfs/usr/lib/firmware/brcm/
###

FROM scratch

COPY --from=builder /target-rootfs/ /

LABEL containers.bootc 1
LABEL ostree.bootable 1

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
